# Default values for odoo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: registry.cloudclusters.net
  app:
    repository: test/odoo
    pullPolicy: IfNotPresent
    tag: "0.0.16-develop"

  agent:
    repository: cloudclusters/mysql5.7-agent
    pullPolicy: IfNotPresent
    tag: "0.0.2-shardagent"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

odoo:
  odoo_password: cloudclusters
  odoo_email: aa.xx@xx.com
  master_password: cloudclusters
  odoo_database: admin
  odoo_demo_database: odoo

postgres:
  postgres_password: cloudclusters
  postgres_user: admin
  postgres_db: admin

  
serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations:
      prometheus.io/path: /metrics
      prometheus.io/port: "9001"
      prometheus.io/scrape: "true"


podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
#   sharing_key: key-test3-4
#   odoo:
#     port: 6379
#   api:
#     port: 60000

secret:
  enabled: true
  crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQyRENDQWNBQ0ZDTWhFeVh5cnBWS2p5OFliNkgzaDB4bjVsN0pNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1EQXgKRGpBTUJnTlZCQW9NQlZKbFpHbHpNUjR3SEFZRFZRUUREQlZEWlhKMGFXWnBZMkYwWlNCQmRYUm9iM0pwZEhrdwpIaGNOTWpBd09URTBNRFl3TkRFMldoY05NakV3T1RFME1EWXdOREUyV2pBaE1RNHdEQVlEVlFRS0RBVlNaV1JwCmN6RVBNQTBHQTFVRUF3d0dVMlZ5ZG1WeU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0MKQVFFQTBEdkNDZmtlQWZjOHB3Rm41RTlyQjcwVFdEWW05RWxPaDI4ZzBXeVZ6MXRXY3RzWTNVdW1PWW9UeEZNaQpLNEd5WEwzeUpNWjkxWE1LSERmRWdjTmJLQjRSak4xNlJZcEdVd2dsa3hEUlJFdm1Nc3YvaEZvdkllaTJWY1FrCnU3cTNhQ2lrV3BzNjJzTTlTc1BpYzlTazhWTk5oeXNsVkgxUS9Pb2ZteEZrSElxSGt5ckR0UmNPYWoxY2plQWsKL3JLQXQ5eWg4bWtUMWlBNy9NdjVFYVFVSFF0VFViV1F3UWZpR3JFWWxHV0NVelR5R0VmRi81b3FHYmF1Z3dkcAp2OEc1NnpwUDZsMzR4c0w0SzlKeXdSN2JmQXBiVDRUTmhKOURFdXRqR3VMY2tscnhtOGtDVG4xSzh0cTQyZkdRClY2emk5TTd0dTQvSGRQR3A3V1d1SGNXdndRSURBUUFCTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElDQVFBVDNFK3QKMVdvaWcreDM1a2FQVlBCODMxNE9KTmNkU3FJQW9wVUoyaURxaEFYZ1pPaDNpSUxpcmNtZm02bitUb0FxN0Z1TwphKzlRT2UxVlVnSzhQQ2h2QmZBRW9weUt0RkVnUnJJejdzL2ZCN2E0aEVVdG05MXJtSkhRNnpORUJvWFVtaGxHCjFlcFRjcktDdnYxTXpIZXQ2MVFIUlFKdGRqcERmQ1ZSd2tQd1ZBUExMdWVzM0hrcjFBSDFIbjBJdFpxR1FLdTkKS211OHY4RDZ1U0gxb20rbXJmZ2dqMnFiUUplOFJJSnNlWGpYY3hUa21YbzBnNFlYYVhZMHlsa2J2aXpVa3lQdwpKUGFNZ3FMWWxNT2lPV2lUVExKUmpvSEtjWm1XYzlVZjZoTDZaeXVSRWp2cVh5RXE4NjAzS2pTdzFnNG51TGw2ClBNWkllMjBQOWx5a20rRFp2b0dZVzY1bmoyWHRIQzdDdDI1Y1F0c0puV2lpU0YvRm1VSEJBR2hTVXk4UW12YlcKOUpsQ2dZQ2pyKy9NTW0yMTEzVXptczBTSFlXdVVjU2hWVWR2c0NPU1B5Z3lEUEUwN1hqNEV0SXkxMFdBOVJFTwozNk0vbmFmTXZ6dzRUa1FDa1FWTXkreEhqV1RBMUc5MXJUcTdvWG1DQ3dtWjNkWEFOWlJPaC9TenJ4QkFCUGxsCnpSUCtDNVAvRWpPL1h1Sm5ZeTF2N0xoMjBjODBSZGJVemE4SHZWTk14YUN3UmZXQ04wdGZ3VTg3bzlLY0RtcjcKbWFFZUNaQUZEa3BSc3pjejZSd3Z4WlplRFVBL3N6M3dPcGZkS2NaWmFpWDljNk9XQm04R0FrZm1iNlQvN1dWSApmcHpkNStqOFQybEtSWlVFYlVXLzBJSkJBOHFkMHhoUkFhSzRQQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBMER2Q0Nma2VBZmM4cHdGbjVFOXJCNzBUV0RZbTlFbE9oMjhnMFd5VnoxdFdjdHNZCjNVdW1PWW9UeEZNaUs0R3lYTDN5Sk1aOTFYTUtIRGZFZ2NOYktCNFJqTjE2UllwR1V3Z2xreERSUkV2bU1zdi8KaEZvdkllaTJWY1FrdTdxM2FDaWtXcHM2MnNNOVNzUGljOVNrOFZOTmh5c2xWSDFRL09vZm14RmtISXFIa3lyRAp0UmNPYWoxY2plQWsvcktBdDl5aDhta1QxaUE3L012NUVhUVVIUXRUVWJXUXdRZmlHckVZbEdXQ1V6VHlHRWZGCi81b3FHYmF1Z3dkcHY4RzU2enBQNmwzNHhzTDRLOUp5d1I3YmZBcGJUNFROaEo5REV1dGpHdUxja2xyeG04a0MKVG4xSzh0cTQyZkdRVjZ6aTlNN3R1NC9IZFBHcDdXV3VIY1d2d1FJREFRQUJBb0lCQUhjR3dYcGI2SGd0TDRFeQp2NFQwbEhSZThuREl1Mm1GZ1pyT3ZjNlhwK1pZQ2trcXpjS28zRUlsbC9qdm9DZUlRa0RhM2srQkdpcHBVSTBpCm4zT2hERGtaUHVUck1Gb1JtUE1iUkFjVlpOa0tIWEpKd3l1UE5VUEh0bm05M1ZWbGZETFFrR211TTIwYWpxMXUKM01GaStrbHJXWFI3Q0NLTVl6KytRQVN1WXpBZ1FvdURoSVFuNVpraHc0ZER0azEwMWhOc2FqTW0zbHhPcFp1UgpFMXg1cDdKNHFjSmE3dWZGb0lybzA2UXhxMEtDUGgvWExCeEZLRFkrUEN5TVJncE1wSFBTY1hGSWR4UW9HUnFRCkpTMGUyanRiY2lkY1VQcnFqZVY4ME1FWDBnSlR2RzdiVGFIc1kwY1pYa2JQdWI1Tytla212NnJrZ1NZRnBTeHYKQUpuelBoVUNnWUVBK0R6ZVp5bDJ2MHdON2ZYUmNSY01OQnUxQUhvVnFWeDFFQktyODkyNlF3TjBYbm1rT0l5YQphdGVlWUJnOTh2UjhEWDdnR2JiajZTSGRQWUtSRC9SNlRucUZFejk2bzIwS1pURjIybFBtNUV1bWhtVnl4ampICmVQTnRDNWJaYjhnY0JpTSsxRktLZ1FITzVWT1JhQWxtNGtvai9QOGt3MDhLNnVLV2tQNHI1dWNDZ1lFQTFyNm8KQ3cvTlgyVlF5SHc0eWNCVmZqcHRzWE5KOUZodm1pUlJHNW1pU3hoNjZuYWdoK1NVQVpac0VZZG1tdmM0cHlLOQp4YVFoNENhL0c2Z0NmS2Z6VnJDVHZpdGUxTFVQWEh6ZUZNNXNDVm9OQk02RzhEbE9XMWNtVmJuWGp1YzVCRjU4CkFNYjNURGxpVlJzTzJpekw5T3psYXhBaGJncGxsaXM3N1g0TFp4Y0NnWUJBOWJ6RmhrWTYzUzR2L1VubnJENVgKVElEYk5SZUNFRjNaN09qdWtqRng0KytKNFk4bDlUVmJqRDAzckdCWnVielUwMFRWdGRTQ1o0ZzcxblVibGNDRAoxUEFLRDJ5S1k3aDZycTBKaVRjOHVzZERHRDBtdmlrRTc3NnpiN0JLM2pUbkxrWDh6ZlRNdWFwb3ZLdXFhL3R1CmNEUm11bVhtYmtMUElLaUNIT0ZrTlFLQmdRRFVSVlk2eVA0TGhFemNRTjZwbjNOaStVS2hIQU5JZzNxZDliUXYKQWlqSTdvUGg3QzAyNXgzZWkrQjdXMHB6ZUZrSjdXK0ZSSDh2NFYwYmEzSTU0cExKYUhaQ2p3Q0laZ212Tk1jWgo3Z29oSEdDdUZiQ1JHVFI1V2FaTkt3MEc5MDBISXBhVTloaFJ3bytPN05ZN2wvaHNQUmR5UTFtb09xSzhWRFJDCnlFdGhOUUtCZ1FEeEdHQUJDU1J5VVZhYzdXNEZGS1RMdDgvYTlaTVhsTkthM1hTR2YyNlFVUFdNd0o3dHM3KzkKckNPOFN3ZndqL1U3bHpERWNiNmd0OFp1VjJQNHJuQ1VGYjJrVkNwYTBEUUJuMkhteDRLWHNKeFhGQzFlMUx4TApKbk5GTVVkdGRLUlkvWjYrTWdJQThVUFBGV2xRSkdLcjJHRis2czFmL1ZleHlWbVhzTFF3Z3c9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
  ca: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZRVENDQXltZ0F3SUJBZ0lVV1RSNXZoUG92WlVRMDViYURhVy9XWWhXUm1rd0RRWUpLb1pJaHZjTkFRRUwKQlFBd01ERU9NQXdHQTFVRUNnd0ZVbVZrYVhNeEhqQWNCZ05WQkFNTUZVTmxjblJwWm1sallYUmxJRUYxZEdodgpjbWwwZVRBZUZ3MHlNREE1TVRRd05qQTBNVFphRncwek1EQTVNVEl3TmpBME1UWmFNREF4RGpBTUJnTlZCQW9NCkJWSmxaR2x6TVI0d0hBWURWUVFEREJWRFpYSjBhV1pwWTJGMFpTQkJkWFJvYjNKcGRIa3dnZ0lpTUEwR0NTcUcKU0liM0RRRUJBUVVBQTRJQ0R3QXdnZ0lLQW9JQ0FRQzJGUWh1QnQvRkh1OWNpb0VHRHkwY3JPblY0eXd1czRYKwpNTzdKNXBqWnBYdUloTXlHZlcwSGFybGk4RHlZMlNPT3Q1RHFNY2tkd0F5TGZlcW1YUE5IVHlUK0VwQnllV3UzCjYwVXdzd1NZWDF2anZib3BTVXd2aDk1S093bGc0dzAzWitINXpjZERiK1EzTXEzRGs2TWlyV2N5cm9kdU44UGQKNEFDNGNDclR2c3hRTHNpYzdEaGZHMkVJRHpodjk4RFJLdHVsVVRCcDhPTWluV1JUcVAyS3J1K3Y5c3JCODJJVQowcXJmT2FIa2RTeFhJeWhxb3h5alF2eUE1ZGlpRlFXWk5kMCt2SGltS2k3RzFwajdJT0tsODVUMG4xcCt1Mk12ClhFUnJmeS8xcE8zQnd2ZjVUMGEvbEFZUlV1NlJBQjdia0lmbDgwVFZIMFVIbmtXRDlUbUNvVGVwNUlVdjUva0UKQ1VGOG9qZGlBWjBOZHVUYzdaT0pnYXgyWVNWanZvL2l5UDBKdURPOW5mMFZ1bWd0dzJweUJ3QUliNlZueGFDYQp1NUJnVVAzOXN0STA0Tm9TOHFLMnRpVS8ySkdyeHg3ekhGN2FPVEFEMlVxemNVV3BDY3AzZGxPaHU5MFhlNHhSCjlLbDhNTUZnN0V5K3FIZGxESllXa0FpdW9OQnhsa0hnaTlPN1IraHJ3ckZEZDVJWnprM000ZVZXNnJGV0MwUFgKL25KSytldll0OHRnd2d0K3BteVV0d1RjdmlBTXRFNll6REFJL2ZNVGI0a09CdFhBWnZjc3l3NXpoUUl0UUlVNAprQ29vREppcEdBMHVNRmU2OEFEdFpURnE1aUZCMlFzL1prUXlRbUNzajdRSURCUU1yUDJpQk04S1p3WmlpYW1hCllqNlFSMGZUY3dJREFRQUJvMU13VVRBZEJnTlZIUTRFRmdRVVlkYklmWHZOajVLSnMwZkJVWlVxUDUxV2lVd3cKSHdZRFZSMGpCQmd3Rm9BVVlkYklmWHZOajVLSnMwZkJVWlVxUDUxV2lVd3dEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBZ0VBQnZRSkQ5U0VSaGJXTjhndkkvRnBaOTk1ZFpqeXR6TVVyRTcwCkNjNG95RFlYanhSeDBzMXo2T0l1Qm5pb1g2NHBoblErWURxVk1tRmloQ25OTzRTSS9GT0U2VTJnSnhMci9VNFoKZFEwR3VXUjlyZDBiRllFdEFjb2FKV3RvOHhlKzIwRUdvK0I0SDJtd2FXaW5NYmVTNFMraCtjZ0lHWmNOdWIwMQpaOWNIeGRXV2NxNUpWSFRzTXBEWWZHMUorRVJVbkg3ejlwMWF4WGFOR3U5L29sbXlvb2FZSUl5Y3NhK2FIZFZiCnpJUjdmMlFEU3dwL0xhTnBPY25ISHdvbDRvbHRyYjAxYmUvaitIbEFKeVl4bk5TT3VpbXhXTkMwQkJIMWFJTVMKQStsUDJ5aDhDak1qV2VOaGdwUnNGV0kxZmhDUzV5enZqLzEvRWJ5Sm9EeTJBRjZlc2dMTXV2MU1ycFRta2IwdgpJcnlFRTZiNkRmY0ZYVC9VWkx3UGZLeXJMR2JBUFFEU1Qweks3MnNHRnZObzlWcmxzblpOOXNSL0grZTJaTmNUCklSVU5YNmVqS1Y5YTJheC9wTm9UOHNNSVRFMGkzOHFUY2NFNDlEUzQvUHdCQll6c1FJYXA1cHdwNDBUOGgwbzYKSUlMNklqWmJlYXk2U2hXN21NeCtwbFY5RURnV29KZndiQmo5UlFiOEFTZE4vQ2REZ3lRQTJCcW5LQ2NzdnhZTAp1UGdGbXM4YVlyeXhNOWpJTS9iQTNmQzNKT3dSeVMxRk5SZnAvZzhueWl6TW1LOTV5cU5SanBMVzVwa2w4eHdICkxFUURheG5yZWd5U2hJMCs0RnY5b0JSeC83WXhwQ1pHSE43RGtXSFBhZyt2V0RpdzhuZTYwN1F1eEcxU3Z2N1MKWXpYWlRuRT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=

ingress:
  enabled: true
  hostname: web.test.com  
  tls: 
  - secretName: certificates
    hosts:
      - web.test.com

resources:
   limits:
     cpu: 2000m
     memory: 2G
   requests:
     cpu: 100m
     memory: 128Mi

livenessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 30
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3
readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 30
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled:  true
  existingClaim: {}
  annotations: 
    volume.beta.kubernetes.io/storage-class: rbd
  accessModes: 
    - ReadWriteOnce    
  size: 20Gi    


agent:
  enabled: true


filebrowser:
  username: admin
  password: SQmc3JOh


