{{- if .Values.ingress.enabled }}
{{- $releaseName := .Release.Name -}}
apiVersion: {{ template "odoo.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ template "odoo.fullname" . }}
  labels: {{- include "odoo.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.annotations }}
    {{- include "odoo.tplValue" (dict "value" .Values.ingress.annotations "context" $) | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- if .hosts }}
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
        {{- else }}
        - {{  printf "%s-0.tripanels.com" ( $releaseName )  }}          
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .Values.ingress.hostname }}
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "odoo.fullname" . }}
              servicePort: http
          - backend:
              serviceName: {{ template "odoo.fullname" . }}
              servicePort: 5001
            path: /cp-agent-api
          - backend:
              serviceName: {{ template "odoo.fullname" . }}
              servicePort: 8000
            path: /filebrowser
    {{- end }}
{{- end }}