{{ if .Values.secret -}}
apiVersion: v1
kind: Secret
metadata:
  name:  {{ include "odoo.fullname" . }}
  labels:
    {{- include "odoo.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.postgres.postgres_password | b64enc | quote }}
  ODOO_PASSWORD: {{ .Values.odoo.odoo_password | b64enc | quote }}
  MASTER_PASSWORD: {{ .Values.odoo.master_password | b64enc | quote }}
  FB_PASSWORD: {{ .Values.filebrowser.password | b64enc | quote }}
{{- end }}