apiVersion: v1
kind: Service
metadata:
  name: {{ include "odoo.fullname" . }}
  labels:
    {{- include "odoo.labels" . | nindent 4 }}
    service_type: public
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
    - name: filebrowser
      port: 8000
      protocol: TCP
      targetPort: 8000
    - name: server-port
      port: 5001
      protocol: TCP
      targetPort: 5001
  selector:
    {{- include "odoo.selectorLabels" . | nindent 4 }}  
